import Foundation

// MARK: - Pre-computed Kubelka-Munk lookup table
//
// Loads ios/RefPlane/PigmentLookup.bin (generated by scripts/precompute_lookup.py).
//
// Binary layout — see script header for full spec.
// In brief:
//   24-byte header  →  Section A (pair entries)  →  Section B (triplet entries)
//
// Each entry is 10 bytes:
//   [0]   i0      UInt8   slot-0 global pigment index
//   [1]   i1      UInt8   slot-1 global pigment index
//   [2]   i2      UInt8   slot-2 global pigment index (0 for pair entries)
//   [3]   packed  UInt8   (a0 << 4) | a1;  a2 = 8 – a0 – a1 (triplet only)
//   [4-5] L       Float16 Oklab L
//   [6-7] a       Float16 Oklab a
//   [8-9] b       Float16 Oklab b

// MARK: - Raw entry (for cold-path recipe construction only)

struct KMLookupEntry {
    let i0, i1, i2: UInt8
    let packed: UInt8

    let L_bits: UInt16
    let a_bits: UInt16
    let b_bits: UInt16

    var a0: Int { Int(packed) >> 4 }
    var a1: Int { Int(packed) & 0xF }
    var a2: Int { 8 - a0 - a1 }

    var color: OklabColor {
        OklabColor(
            L: Float(Float16(bitPattern: L_bits)),
            a: Float(Float16(bitPattern: a_bits)),
            b: Float(Float16(bitPattern: b_bits))
        )
    }

    func paintCount(isTriplet: Bool) -> Int {
        let a0 = self.a0, a1 = self.a1
        if isTriplet {
            return (a0 > 0 ? 1 : 0) + (a1 > 0 ? 1 : 0) + ((8 - a0 - a1) > 0 ? 1 : 0)
        } else {
            return (a0 > 0 ? 1 : 0) + (a1 > 0 ? 1 : 0)
        }
    }
}

// MARK: - Lookup table

final class PigmentLookupTable {

    // MARK: Header fields

    let pigmentCount: Int
    let pairCount: Int
    let tripletCount: Int
    let pairSteps: Int
    let tripletSteps: Int
    let resolution: Int

    // MARK: Zero-copy storage

    /// Retains the memory-mapped file data.
    private let data: Data

    /// Pre-converted Float32 Oklab: oklabBuffer[entryIndex * 3 + 0/1/2] = L/a/b.
    /// Contiguous for cache-friendly hot-loop access in findBest.
    private let oklabBuffer: [Float]      // totalEntries × 3

    private let pairEntryCount: Int       // pairCount × pairSteps

    // MARK: O(1) index arrays

    private let pairIndex: [Int32]        // [i * N + j] → pair rank; −1 if i ≥ j
    private let tripletIndex: [Int32]     // [i * N² + j * N + k] → triplet rank

    // MARK: Init

    init(url: URL) throws {
        let d = try Data(contentsOf: url, options: .mappedIfSafe)
        guard d.count >= 24 else { throw LoadError.tooSmall }

        func le32(_ d: Data, _ off: Int) -> Int {
            Int(d[off]) | (Int(d[off+1]) << 8) | (Int(d[off+2]) << 16) | (Int(d[off+3]) << 24)
        }
        func le16(_ d: Data, _ off: Int) -> Int {
            Int(d[off]) | (Int(d[off+1]) << 8)
        }

        guard d[0..<4] == Data("KMLT".utf8) else { throw LoadError.badMagic }

        let N  = Int(d[5])
        let res = le16(d, 6)
        let pc = le32(d, 8)
        let tc = le32(d, 12)
        let ps = le32(d, 16)
        let ts = le32(d, 20)

        pigmentCount  = N
        resolution    = res
        pairCount     = pc
        tripletCount  = tc
        pairSteps     = ps
        tripletSteps  = ts
        pairEntryCount = pc * ps

        let totalEntries = pc * ps + tc * ts
        guard d.count >= 24 + totalEntries * 10 else { throw LoadError.truncated }

        // Pre-convert Float16 → Float32 in a single pass.
        // This eliminates per-check Float16 conversion in the hot findBest loop.
        var oklab = [Float](repeating: 0, count: totalEntries * 3)
        d.withUnsafeBytes { raw in
            let base = raw.baseAddress!.advanced(by: 24)
            for i in 0..<totalEntries {
                let p = base.advanced(by: i * 10 + 4)
                oklab[i * 3]     = Float(Float16(bitPattern: p.load(fromByteOffset: 0, as: UInt16.self)))
                oklab[i * 3 + 1] = Float(Float16(bitPattern: p.load(fromByteOffset: 2, as: UInt16.self)))
                oklab[i * 3 + 2] = Float(Float16(bitPattern: p.load(fromByteOffset: 4, as: UInt16.self)))
            }
        }
        oklabBuffer = oklab
        data = d

        // Build pair index
        var pi = [Int32](repeating: -1, count: N * N)
        var rank = 0
        for i in 0..<N {
            for j in (i + 1)..<N {
                pi[i * N + j] = Int32(rank)
                rank += 1
            }
        }
        pairIndex = pi

        // Build triplet index
        var ti = [Int32](repeating: -1, count: N * N * N)
        rank = 0
        for i in 0..<N {
            for j in (i + 1)..<N {
                for k in (j + 1)..<N {
                    ti[i * N * N + j * N + k] = Int32(rank)
                    rank += 1
                }
            }
        }
        tripletIndex = ti
    }

    // MARK: - Cold-path entry access (for recipeFromTable)

    /// Read a single KMLookupEntry from the mmap'd file at the given flat index.
    func readEntry(at index: Int) -> KMLookupEntry {
        data.withUnsafeBytes { raw in
            let p = raw.baseAddress!.advanced(by: 24 + index * 10)
            let b = p.assumingMemoryBound(to: UInt8.self)
            let u = p.advanced(by: 4).assumingMemoryBound(to: UInt16.self)
            return KMLookupEntry(
                i0: b[0], i1: b[1], i2: b[2], packed: b[3],
                L_bits: u[0], a_bits: u[1], b_bits: u[2]
            )
        }
    }

    // MARK: - Hot-path best-match search

    /// Find the closest colour match across all enabled pair/triplet combinations.
    ///
    /// The inner loop operates on the pre-converted Float32 oklabBuffer with direct
    /// array indexing — no struct construction, ArraySlice, or Float16 conversion per check.
    func findBest(
        for target: OklabColor,
        enabledGlobalIndices: [Int],
        maxPigments: Int
    ) -> (entry: KMLookupEntry, distSq: Float)? {
        let enabled = enabledGlobalIndices
        let M = enabled.count
        guard M > 0 else { return nil }

        let N = pigmentCount
        let ps = pairSteps
        let ts = tripletSteps
        let pec = pairEntryCount
        let tL = target.L, ta = target.a, tb = target.b

        var bestIdx = -1
        var bestDist = Float.greatestFiniteMagnitude

        oklabBuffer.withUnsafeBufferPointer { oklab in
            pairIndex.withUnsafeBufferPointer { pi in
                // ── Pairs: covers all 1-paint and 2-paint combos ────────────
                for a in 0..<M {
                    let iN = enabled[a] * N
                    for b in (a + 1)..<M {
                        let rank = Int(pi[iN + enabled[b]])
                        guard rank >= 0 else { continue }
                        let base = rank * ps
                        if maxPigments >= 2 {
                            // All pair entries have paintCount ≤ 2 — no filter needed.
                            for s in 0..<ps {
                                let oi = (base + s) * 3
                                let dL = oklab[oi] - tL
                                let da = oklab[oi + 1] - ta
                                let db = oklab[oi + 2] - tb
                                let d = dL * dL + da * da + db * db
                                if d < bestDist { bestDist = d; bestIdx = base + s }
                            }
                        } else {
                            // maxPigments == 1: only pure-pigment entries (steps 0 and ps−1).
                            for s in [0, ps - 1] {
                                let oi = (base + s) * 3
                                let dL = oklab[oi] - tL
                                let da = oklab[oi + 1] - ta
                                let db = oklab[oi + 2] - tb
                                let d = dL * dL + da * da + db * db
                                if d < bestDist { bestDist = d; bestIdx = base + s }
                            }
                        }
                    }
                }
            }

            // ── Triplets: covers 3-paint combos ─────────────────────────────
            if maxPigments >= 3 {
                tripletIndex.withUnsafeBufferPointer { ti in
                    let N2 = N * N
                    for a in 0..<M {
                        let iN2 = enabled[a] * N2
                        for b in (a + 1)..<M {
                            let ijN = iN2 + enabled[b] * N
                            for c in (b + 1)..<M {
                                let rank = Int(ti[ijN + enabled[c]])
                                guard rank >= 0 else { continue }
                                let base = pec + rank * ts
                                // All triplet entries have paintCount ≤ 3 — no filter.
                                for s in 0..<ts {
                                    let oi = (base + s) * 3
                                    let dL = oklab[oi] - tL
                                    let da = oklab[oi + 1] - ta
                                    let db = oklab[oi + 2] - tb
                                    let d = dL * dL + da * da + db * db
                                    if d < bestDist { bestDist = d; bestIdx = base + s }
                                }
                            }
                        }
                    }
                }
            }
        }

        guard bestIdx >= 0 else { return nil }
        return (readEntry(at: bestIdx), bestDist)
    }

    // MARK: - Precomputed masstone colours

    lazy var masstones: [OklabColor] = {
        let N = pigmentCount
        let ps = pairSteps
        var result = [OklabColor](repeating: OklabColor(L: 0, a: 0, b: 0), count: N)
        // Pair (0,1) step ps-1 → pure pigment 0
        let rank0 = Int(pairIndex[1])   // pairIndex[0 * N + 1]
        if rank0 >= 0 {
            let oi = (rank0 * ps + ps - 1) * 3
            result[0] = OklabColor(L: oklabBuffer[oi], a: oklabBuffer[oi + 1], b: oklabBuffer[oi + 2])
        }
        // Pair (0,i) step 0 → pure pigment i
        for i in 1..<N {
            let rank = Int(pairIndex[i])  // pairIndex[0 * N + i]
            if rank >= 0 {
                let oi = (rank * ps) * 3
                result[i] = OklabColor(L: oklabBuffer[oi], a: oklabBuffer[oi + 1], b: oklabBuffer[oi + 2])
            }
        }
        return result
    }()

    // MARK: - Errors

    enum LoadError: Error {
        case tooSmall, badMagic, truncated
    }
}
